#!/usr/bin/python3
import random
import string

letter=int(input("How many letters do you want in your code?"'\n'))
letters=string.ascii_lowercase

number=int(input("How many numbers do you want in your code?"'\n'))
numbers=string.digits

symbol=int(input("How many symbols do you want in your code?"'\n'))
symbols=string.punctuation

list = []
for _ in range(letter):
    list.append(random.choice(letters))
for _ in range(number):
    list.append(random.choice(numbers))
for _ in range(symbol):
    list.append(random.choice(symbols))

random.shuffle(list)

password = ""

for input in list:
    password += input
print(password)
